import React, { useState, useEffect } from "react"
import Head from "next/head"
import { Link as ScrollLink, Element } from "react-scroll"
import Link from "next/link"
import styles from "@/styles/Home.module.css"
import albums from "../../public/albums.json"

export default function Home() {
  const [hovered, setHovered] = useState(false)

  return (
    <>
      <Head>
        <title>Miop personal site</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.screen}>
          <nav className={styles.header}>
            <ScrollLink to='releases' smooth={true} duration={500}>
              releases
            </ScrollLink>
            <ScrollLink to='about' smooth={true} duration={500}>
              about
            </ScrollLink>
          </nav>

          <div className={styles.title}>
            <h1
              className={styles[`${hovered ? "animated-text" : ""}`]}
              onMouseEnter={() => setHovered(true)}
              onMouseLeave={() => setHovered(false)}
            >
              miop
            </h1>
          </div>
        </div>

        {/* releases */}
        <Element className={styles.screen} name='releases'>
          <div className={styles.releases}>
            {Object.keys(albums).map((slug, index) => (
              <Link
                key={slug}
                href='/[slug]'
                as={`/${slug}`}
                className={styles[`${index === 0 ? "releases-active" : ""}`]}
              >
                {albums[slug as keyof typeof albums]?.title}{" "}
                <span>{albums[slug as keyof typeof albums]?.year}</span>
              </Link>
            ))}
          </div>
        </Element>

        <Element className={styles.screen} name='about'>
          <p className={styles.about}>
            It is a long established fact that a reader will be distracted by
            the readable content of a page when looking at its layout. The point
            of using Lorem Ipsum is that it has a more-or-less normal
            distribution of letters, as opposed to using 'Content here, content
            here', making it look like readable English. Many desktop publishing
            packages and web page editors now use Lorem Ipsum as their default
            model text, and a search for 'lorem ipsum' will uncover many web
            sites still in their infancy. Various versions have evolved over the
            years, sometimes by accident, sometimes on purpose (injected humour
            and the like).
          </p>

          <div className={styles.socials}>
            <div>
              <a href='https://www.instagram.com/miop.artist/' target='_blank'>
                inst•
              </a>
              <a href='https://t.me/bogart_coder/' target='_blank'>
                tg•
              </a>
            </div>

            <a
              href='https://linktr.ee/miop.artist/'
              target='_blank'
              className={styles.listen}
            >
              listen
            </a>
          </div>
        </Element>
      </main>
    </>
  )
}
